# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jarvisgui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1162, 644)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -20, 1181, 691))
        self.label.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label.setText("")
        self.label.setScaledContents(False)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(370, 50, 401, 571))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("data/mainf.gif"))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(770, 540, 391, 81))
        self.label_3.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("data/inslization.gif"))
        self.label_3.setScaledContents(False)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(830, 480, 141, 51))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("data/singlebutton.jpg"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(1020, 480, 141, 51))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("data/singlebutton.jpg"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(850, 492, 101, 31))
        self.pushButton.setStyleSheet("background: transparent;\n"
"color: rgb(238, 238, 236);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1040, 492, 101, 31))
        self.pushButton_2.setStyleSheet("background: transparent;\n"
"color: rgb(238, 238, 236);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_4.setGeometry(QtCore.QRect(120, 40, 81, 41))
        self.textBrowser_4.setStyleSheet("background:transparent;\n"
"color: rgb(2, 174, 173);\n"
"font: 75 12pt \"Umpush\";\n"
"")
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(20, 30, 151, 91))
        self.textBrowser_2.setStyleSheet("background:transparent;\n"
"color:white;\n"
"font: 75 30pt \"Umpush\";")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(148, 45, 141, 41))
        self.textBrowser.setStyleSheet("background:transparent;\n"
"color:white;\n"
"font: 75 10pt \"Umpush\";")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_3.setGeometry(QtCore.QRect(119, 56, 201, 51))
        self.textBrowser_3.setStyleSheet("background:transparent;\n"
"color:white;\n"
"font: 75 15pt \"Umpush\";")
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_5.setGeometry(QtCore.QRect(20, 90, 301, 41))
        self.textBrowser_5.setStyleSheet("background:transparent;\n"
"color: rgb(2, 174, 173);\n"
"font: 75 10pt \"Umpush\";\n"
"")
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.textBrowser_6 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_6.setGeometry(QtCore.QRect(830, 90, 321, 371))
        self.textBrowser_6.setStyleSheet("border-color: rgb(2, 174, 173);\n"
"border-right-color: rgb(2, 174, 173);\n"
"background:transparent;")
        self.textBrowser_6.setObjectName("textBrowser_6")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "START"))
        self.pushButton_2.setText(_translate("MainWindow", "STOP"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
